title: Companion, TheCube Docs
description: Official documentation for TheCube, TheCube-Core, apps, SDK, and TheCube+
url: https://docs.4thecube.com
baseurl: ""                      # keep empty for apex docs site

# Use the Just the Docs theme via remote_theme (works on GitHub Pages)
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

logo: /assets/images/logo.svg
favicon_ico: /assets/images/logo.svg

# Just-the-Docs options
just_the_docs:
  navigation_depth: 2
  search_enabled: true
  heading_anchors: true
  show_navbar: true
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"


color_scheme: dark

# Footer links
aux_links:
  "GitHub Repo":
    - "https://github.com/Companion-TheCube/Companion-TheCube.github.io"
  "Discord":
    - "https://discord.gg/WtbhWy82qP"
  "Kickstarter":
    - "https://www.kickstarter.com/projects/a-mcd/1425468019"
aux_links_new_tab: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude junk from the site
exclude:
  - .github/
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/

collections: {
  "apps": {
    "output": true,
    "permalink": "/apps/:path/"
  },
  "core": {
    "output": true,
    "permalink": "/core/:path/"
  },
  "cloud": {
    "output": true,
    "permalink": "/cloud/:path/"
  },
  "hardware": {
    "output": true,
    "permalink": "/hardware/:path/"
  },
  "thecube-plus": {
    "output": true,
    "permalink": "/thecube-plus/:path/"
  },
  "community": {
    "output": true,
    "permalink": "/community/:path/"
  },
  "getting-started": {
    "output": true,
    "permalink": "/getting-started/:path/"
  },
  "api": {
    "output": true,
    "permalink": "/api/:path/"
  }
}

defaults:
  - scope:
      type: "getting-started"
    values:
      parent: "Getting Started"
  - scope:
      type: "core"
    values:
      parent: "TheCube Core"
  - scope:
      type: "apps"
    values:
      parent: "App Development"
  - scope:
      path: "built-in"
      type: "apps"
    values:
      parent: "Built-in Apps"
      grand_parent: "App Development"
  - scope:
      type: "cloud"
    values:
      parent: "TheCube+ Cloud"
  - scope:
      type: "hardware"
    values:
      parent: "Hardware"
  - scope:
      type: "community"
    values:
      parent: "Community"
  - scope:
      type: "api"
    values:
      parent: "API"
  - scope:
      type: "thecube-plus"
    values:
      parent: "TheCube+"

